# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-02-01 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180201_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='email',
            field=models.EmailField(max_length=20, verbose_name='邮箱'),
        ),
    ]
